owner: trybunce # Your GitHub organization or username, where this repository lives
repo: bunce-uptime # The name of this repository

sites:
  - name: Bunce Docs
    url: https://developers.bunce.so
    
  - name: Bunce App
    url: https://app.bunce.so
    
  - name: Bunce Base
    url: https://base.bunce.so
    maxResponseTime: 1200
    
  - name: Bunce Sandbox
    url: https://sandbox.bunce.so
    
  - name: Bunce APIs
    url: https://api.bunce.so
    
  - name: Bunce APIs (Sandbox)
    url: https://sandbox.api.bunce.so
    maxResponseTime: 600

  - name: Bunce Ingest
    url: https://events.bunce.so
    maxResponseTime: 600

  - name: Bunce Blog
    url: https://blog.bunce.so

assignees:
  - dammy001
  - paulayuk

status-website:
  baseUrl: /bunce-uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Bunce-Uptime
  introTitle: "Monitor Bunce Uptime"
  navbar:
    - title: Status
      href: /
    - title: Bunce Uptime
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
